import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import style from './layout.module.scss'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className={style.layout}>
          <h1>NextJS Experimentation Header</h1>
          {children}
        </section>
        </body>
    </html>
  )
}
